sudo: required
git:
  depth: 3
services:
  - docker
matrix:
  include:
    - env: ubuntu_version="18.04"
script:
  - docker pull lhofmann/paraview-ubuntu:${ubuntu_version}
  - chmod -R 777 .
  - docker run -itd --name build --volume="`pwd`:/mnt:rw" lhofmann/paraview-ubuntu:${ubuntu_version}
  - docker exec build cmake -H/mnt/shared/example -B/mnt/shared/build
  - docker exec build cmake --build /mnt/shared/build --target package
  - docker pull ubuntu:${ubuntu_version}
  - docker run -itd --name test --volume="`pwd`:/mnt:rw" ubuntu:${ubuntu_version}
  - docker exec test apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y paraview
  - docker exec test dpkg -i /mnt/shared/build/Example-0.1.0-Linux.deb
  - docker exec test pvpython /mnt/shared/.travis.test.py
